stages:
  - validate
  - deploy

default:
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y curl unzip
    - curl -fsSL -o databricks.zip https://github.com/databricks/cli/releases/download/v1.9.0/databricks_cli_1.9.0_linux_amd64.zip
    - unzip databricks.zip
    - mv databricks /usr/local/bin/
    - databricks --version

validate_dev_giorgos:
  stage: validate
  script:
    - export DATABRICKS_TOKEN=$DATABRICKS_TOKEN_GIORGOS
    - databricks bundle validate -t dev_giorgos
  only:
    - vrontos-develop

validate_dev_charis:
  stage: validate
  script:
    - export DATABRICKS_TOKEN=$DATABRICKS_TOKEN_CHARIS
    - databricks bundle validate -t dev_charis
  only:
    - Christakidis_Develop

validate_prod:
  stage: validate
  script:
    - databricks bundle validate -t prod
  only:
    - main


deploy_to_dev_giorgos:
  stage: deploy
  script:
    - export DATABRICKS_TOKEN=$DATABRICKS_TOKEN_GIORGOS
    - databricks bundle deploy -t dev_giorgos
  only:
    - vrontos-develop

deploy_to_dev_charis:
  stage: deploy
  script:
    - export DATABRICKS_TOKEN=$DATABRICKS_TOKEN_CHARIS
    - databricks bundle deploy -t dev_charis
  only:
    - Christakidis_Develop

deploy_to_prod:
  stage: deploy
  script:
    - databricks bundle deploy -t prod
  only:
    - main